✨ Complete homework
OlesiaShcherbenko/hw-13-documentation pull request #1
Opened 2024-06-25 05:08 UTC by OlesiaShcherbenko

2024-07-11 15:27 UTC, a1exalexander requested changes

2024-07-11 15:27 UTC, a1exalexander commented on index.html
> +                <li>Who's using</li>
це також посилання!

2024-07-11 15:27 UTC, a1exalexander commented on index.html
> +              <h1>Core components</h1>
https://www.notion.so/sashkoratushnyi/Lesson-18-SCSS-e5defd53689942cea9d3ec9631c5ce47?pvs=4#a1bfc191f4304a63a4e15a21c1e6cc11
На одній сторінці не може бути декілька `<h1>`

2024-07-11 16:57 UTC, OlesiaShcherbenko commented on index.html
> +              <h1>Core components</h1>
Дякую! Я вже ці помилки в who's using виправила, а тут забула. Помилки продублювались, тому що спочатку зверстала documentation, а потім на її основі робила who's using.

2024-07-11 17:03 UTC, OlesiaShcherbenko commented
Виправила помилки 🌿

2024-07-11 17:04 UTC, OlesiaShcherbenko reviewed
Виправила помилки 🌿

2024-10-21 18:10 UTC, a1exalexander approved these changes

2025-03-22 07:33 UTC, merged